services:
  - type: web
    name: persona-matcher-ai
    env: node
    plan: starter
    buildCommand: npm run build:render
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false

      - key: JWT_SECRET
        sync: false
    healthCheckPath: /api/status
    autoDeploy: true
