export interface ArtworkPersonaMapping {
    artworkName: string;
    personaName: string;
    description: string;
}

export const artworkPersonaMappings: ArtworkPersonaMapping[] = [
    { artworkName: "Abstract Leopard", personaName: "The Trailblazing Spirit", description: "Bold, adventurous, and unafraid to stand out with fierce confidence" },
    { artworkName: "African Adventure", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "African Elephant", personaName: "The Quiet Visionary", description: "Thoughtful, introspective, and appreciates subtle elegance and wisdom" },
    { artworkName: "Amazing Amazon", personaName: "The Trailblazing Spirit", description: "Bold, adventurous, and unafraid to stand out with fierce confidence" },
    { artworkName: "Angel Wings", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Basket Embossed Black", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Basket Embossed Caladium Green", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Bel Fiori", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Birds In Paradise Black", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Boho Paisley", personaName: "The Creative Nomad", description: "Free-spirited, eclectic, and embraces cultural diversity and artistic expression" },
    { artworkName: "Butterflies Honey", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Butterfly Blooms Bronze", personaName: "The Wandering Bloom", description: "Graceful, adaptable, and finds beauty in transformation and growth" },
    { artworkName: "Butterfly Heaven", personaName: "The Wandering Bloom", description: "Graceful, adaptable, and finds beauty in transformation and growth" },
    { artworkName: "Butterfly Heaven Ruby", personaName: "The Wandering Bloom", description: "Graceful, adaptable, and finds beauty in transformation and growth" },
    { artworkName: "Butterfly Melody", personaName: "The Wandering Bloom", description: "Graceful, adaptable, and finds beauty in transformation and growth" },
    { artworkName: "Butterfly Mosaic Black", personaName: "The Wandering Bloom", description: "Graceful, adaptable, and finds beauty in transformation and growth" },
    { artworkName: "Calaveras de Azucar", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Camellia Tan", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Canyon Birds", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Cardinal Family", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Caribbean Garden", personaName: "The Serene Seeker", description: "Peaceful, nature-loving, and finds tranquility in organic beauty" },
    { artworkName: "City Lights", personaName: "The Creative Nomad", description: "Free-spirited, eclectic, and embraces cultural diversity and artistic expression" },
    { artworkName: "City of Dreams", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Cleopatra's Leopard", personaName: "The Trailblazing Spirit", description: "Bold, adventurous, and unafraid to stand out with fierce confidence" },
    { artworkName: "Cleopatra's Leopard Tan", personaName: "The Trailblazing Spirit", description: "Bold, adventurous, and unafraid to stand out with fierce confidence" },
    { artworkName: "Crimson Garden", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Croc Embossed Berry", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Croc Embossed Blush Gold", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Croc Embossed Caramel", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Croc Embossed Cream Gold", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Croc Embossed Daydream", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Croc Embossed Desert Gold", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Croc Embossed Peacock", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Croc Embossed Sapphire", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Croc Embossed Silver Gray", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Croc Embossed Wine", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Dancing Leaves", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Deer and Cardinal", personaName: "The Quiet Visionary", description: "Thoughtful, introspective, and appreciates subtle elegance and wisdom" },
    { artworkName: "Denim Paisley Floral", personaName: "The Creative Nomad", description: "Free-spirited, eclectic, and embraces cultural diversity and artistic expression" },
    { artworkName: "Dragon Legend", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Dragonfly Garden", personaName: "The Wandering Bloom", description: "Graceful, adaptable, and finds beauty in transformation and growth" },
    { artworkName: "Dreamy Floral", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Earth Song", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Elephant Mandala", personaName: "The Quiet Visionary", description: "Thoughtful, introspective, and appreciates subtle elegance and wisdom" },
    { artworkName: "Enchanted Garden", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Enigmatic Leopard", personaName: "The Trailblazing Spirit", description: "Bold, adventurous, and unafraid to stand out with fierce confidence" },
    { artworkName: "Ethereal Garden", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Evening Wolves", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Fabulous Flutter Ruby", personaName: "The Joyweaver", description: "Optimistic, vibrant, and spreads happiness through colorful choices" },
    { artworkName: "Feather Skull Denim", personaName: "The Creative Nomad", description: "Free-spirited, eclectic, and embraces cultural diversity and artistic expression" },
    { artworkName: "Floral Charm", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Floral Paradise Tan", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Floral Passion", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Flower Garden Almond", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Flower Garden Taupe", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Free Spirit", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Friendly Flock", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Garden Llama", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Garden of Delights", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Gentle Giant", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Gift of the Sea", personaName: "The Serene Seeker", description: "Peaceful, nature-loving, and finds tranquility in organic beauty" },
    { artworkName: "Guiding Light", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Happy Panda", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Heritage Almond", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Heritage Turquoise", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Herringbone Embossed Black", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Herringbone Embossed Red", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "High Roller", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Himalayan Bird", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Hummingbird Black", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Imperial Tiger", personaName: "The Trailblazing Spirit", description: "Bold, adventurous, and unafraid to stand out with fierce confidence" },
    { artworkName: "India Safari", personaName: "The Trailblazing Spirit", description: "Bold, adventurous, and unafraid to stand out with fierce confidence" },
    { artworkName: "Indian Dream", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Indian Paisley", personaName: "The Creative Nomad", description: "Free-spirited, eclectic, and embraces cultural diversity and artistic expression" },
    { artworkName: "Japanese Garden", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Jungle Queen", personaName: "The Trailblazing Spirit", description: "Bold, adventurous, and unafraid to stand out with fierce confidence" },
    { artworkName: "King of the Jungle", personaName: "The Trailblazing Spirit", description: "Bold, adventurous, and unafraid to stand out with fierce confidence" },
    { artworkName: "Koi Celebration", personaName: "The Joyweaver", description: "Optimistic, vibrant, and spreads happiness through colorful choices" },
    { artworkName: "Ladybug Garden", personaName: "The Wandering Bloom", description: "Graceful, adaptable, and finds beauty in transformation and growth" },
    { artworkName: "Leopard Floral", personaName: "The Trailblazing Spirit", description: "Bold, adventurous, and unafraid to stand out with fierce confidence" },
    { artworkName: "Leopard Mirage", personaName: "The Trailblazing Spirit", description: "Bold, adventurous, and unafraid to stand out with fierce confidence" },
    { artworkName: "Lily Garden Denim", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Lily Garden Tan", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Lively Butterflies", personaName: "The Wandering Bloom", description: "Graceful, adaptable, and finds beauty in transformation and growth" },
    { artworkName: "Lotus Black", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Love in Paris", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Magical Garden", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Majestic Birds", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Mandala in Denim", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Mandala in Rainbow", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Meadow Birds", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Midnight Garden", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Midnight Peacock", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Mosaic Floral", personaName: "The Creative Nomad", description: "Free-spirited, eclectic, and embraces cultural diversity and artistic expression" },
    { artworkName: "Mystic Butterfly", personaName: "The Wandering Bloom", description: "Graceful, adaptable, and finds beauty in transformation and growth" },
    { artworkName: "Mystic Forest", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Mystical Reef", personaName: "The Serene Seeker", description: "Peaceful, nature-loving, and finds tranquility in organic beauty" },
    { artworkName: "Nature's Palette", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Orchid Garden", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Owl Flowers", personaName: "The Quiet Visionary", description: "Thoughtful, introspective, and appreciates subtle elegance and wisdom" },
    { artworkName: "Painted Dream", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Paradise Found", personaName: "The Serene Seeker", description: "Peaceful, nature-loving, and finds tranquility in organic beauty" },
    { artworkName: "Parisian Butterfly", personaName: "The Wandering Bloom", description: "Graceful, adaptable, and finds beauty in transformation and growth" },
    { artworkName: "Peacock Bliss", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Peacock Flower", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Peacock Garden", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Peacock Love", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Peacock Princess", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Peacock Treasure", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Peonies Black", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Peony Bloom", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Poppy Garden", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Rainbow Birds", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Retro Elephant", personaName: "The Quiet Visionary", description: "Thoughtful, introspective, and appreciates subtle elegance and wisdom" },
    { artworkName: "Rose Safari", personaName: "The Trailblazing Spirit", description: "Bold, adventurous, and unafraid to stand out with fierce confidence" },
    { artworkName: "Royal Peacock", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" },
    { artworkName: "Sacred Elephant", personaName: "The Quiet Visionary", description: "Thoughtful, introspective, and appreciates subtle elegance and wisdom" },
    { artworkName: "Savanna Roar", personaName: "The Trailblazing Spirit", description: "Bold, adventurous, and unafraid to stand out with fierce confidence" },
    { artworkName: "Siamese Cats", personaName: "The Creative Soul", description: "Artistic, imaginative, and drawn to unique, expressive designs" },
    { artworkName: "Starry Night", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Tropical Bloom", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Tropical Jungle", personaName: "The Trailblazing Spirit", description: "Bold, adventurous, and unafraid to stand out with fierce confidence" },
    { artworkName: "Tulip Garden", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Turtle Cove", personaName: "The Serene Seeker", description: "Peaceful, nature-loving, and finds tranquility in organic beauty" },
    { artworkName: "Vintage Butterfly", personaName: "The Wandering Bloom", description: "Graceful, adaptable, and finds beauty in transformation and growth" },
    { artworkName: "Whimsical Forest", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Wings of Hope", personaName: "The Dreamteller", description: "Visionary, imaginative, and creates stories through style choices" },
    { artworkName: "Wise Owl", personaName: "The Quiet Visionary", description: "Thoughtful, introspective, and appreciates subtle elegance and wisdom" },
    { artworkName: "Zen Garden", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Rainforest Beauties", personaName: "The Serene Seeker", description: "Peaceful, nature-loving, and finds tranquility in organic beauty" },
    { artworkName: "Island Escape Black", personaName: "The Creative Nomad", description: "Free-spirited, eclectic, and embraces cultural diversity and artistic expression" },
    { artworkName: "Jardin Bleu", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Vibrant Parrot Percheron", personaName: "The Joyweaver", description: "Optimistic, vibrant, and spreads happiness through colorful choices" },
    { artworkName: "Romantic Roses Red", personaName: "The Poetic Soul", description: "Romantic, introspective, and finds meaning in life's delicate moments" },
    { artworkName: "Tooled Dragonfly Meadow Pewter", personaName: "The Wandering Bloom", description: "Graceful, adaptable, and finds beauty in transformation and growth" },
    { artworkName: "Tooled Birds Sky", personaName: "The Radiant Observer", description: "Attentive to beauty, detail-oriented, and values sophisticated aesthetics" }
];

export function findPersonaForArtwork(artworkName: string): ArtworkPersonaMapping | null {
    return artworkPersonaMappings.find(mapping => 
        mapping.artworkName.toLowerCase() === artworkName.toLowerCase()
    ) || null;
} 